//main에 출력
export const FETCH_MAIN_DATA='FETCH_MAIN_DATA'

// food
export const FETCH_FOOD_LIST='FETCH_FOOD_LIST'
export const FETCH_FOOD_DETAIL='FETCH_FOOD_DETAIL'
export const FETCH_FOOD_FIND='FETCH_FOOD_FIND'

// info

export const FETCH_INFO_LIST='FETCH_INFO_LIST'
export const FETCH_INFO_DETAIL='FETCH_INFO_DETAIL'
export const FETCH_INFO_FIND='FETCH_INFO_FIND'

// youtube
export const FETCH_YOUTUBE_FIND='FETCH_YOUTUBE_FIND'

// 값비워주기
export const RESET_RESULT = 'RESET_RESULT';

// board
export const BOARD_LIST='BOARD_LIST'
export const BOARD_DETAIL='BOARD_DETAIL'
export const BOARD_UPDATE='BOARD_UPDATE'
export const BOARD_DELETE='BOARD_DELETE'
export const BOARD_INSERT='BOARD_INSERT'
export const BOARD_UPDATE_OK='BOARD_UPDATE_OK'

export const FETCH_NEWS_LIST='FETCH_NEWS_LIST'