//main에 출력
export const FETCH_MAIN_DATA='FETCH_MAIN_DATA'

export const FETCH_HOTEL_LIST='FETCH_HOTEL_LIST'
export const FETCH_HOTEL_DETAIL='FETCH_HOTEL_DETAIL'
export const FETCH_HOTEL_FIND='FETCH_HOTEL_FIND'

// youtube
export const FETCH_YOUTUBE_FIND='FETCH_YOUTUBE_FIND'


// 값비워주기
export const RESET_RESULT = 'RESET_RESULT';

// board
export const BOARD_LIST='BOARD_LIST'
export const BOARD_DETAIL='BOARD_DETAIL'
export const BOARD_UPDATE='BOARD_UPDATE'
export const BOARD_DELETE='BOARD_DELETE'
export const BOARD_INSERT='BOARD_INSERT'
export const BOARD_UPDATE_OK='BOARD_UPDATE_OK'

//뉴스

export const FETCH_NEWS_LIST='FETCH_NEWS_LIST'


export const FETCH_GUEST_LIST='FETCH_GUEST_LIST'
export const FETCH_LOCATION_LIST='FETCH_LOCATION_LIST'
export const FETCH_SHOP_LIST='FETCH_SHOP_LIST'
export const FETCH_NATURE_LIST='FETCH_NATURE_LIST'